---
title: "Age at Onset Stratified Analysis"
author: "Joshua Hack"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```

```{r}
library(tidyverse)
library(data.table)
library(readxl)
library(mltools)
```

#1. Assigning Groups
```{r}
onset_age <- read.csv("Onset Ages.csv")

onset_age <- data.table(onset_age)
onset_age <- onset_age[, min(Age_onset), by = "UUID"]

onset_age <- onset_age %>% mutate( Onset_group = 
                                     ifelse(V1 <=30, "Neonatal",
                                            ifelse(V1 >30 & V1 <= 120, "1-4 Months",
                                                   ifelse(V1 > 120 & V1 <= 210, "4-7 Months",
                                                          ifelse(V1 > 210 & V1 <=365, "7-12 Months", "12+ Months")))))
study <- onset_age %>% rename("age_onset" = "V1")
study <- study %>% mutate(age_onset_m = age_onset/30)

#write.csv(onset_age, "Onset Groups.csv")
```

#2. Load more data for building out dataset
```{r}
Ciitizen_seizures = read_excel("./Ciitizen_SCN8A_UArizona_2024.02.09.xlsx", sheet = "seizure_history")
Ciitizen_diagnosis= read_excel("./Ciitizen_SCN8A_UArizona_2024.02.09.xlsx", sheet = "clinical_diagnosis")
Ciitizen_variant = read_excel("./Ciitizen_SCN8A_UArizona_2024.02.09.xlsx", sheet = "genetic_findings")
Ciitizen_medication = read_excel("./Ciitizen_SCN8A_UArizona_2024.02.09.xlsx", sheet = "medication_aggregate")
Ciitizen_hospitalization = read_excel("./Ciitizen_SCN8A_UArizona_2024.02.09.xlsx", sheet = "hospital_admission")
Ciitizen_demographics = read_excel("./Ciitizen_SCN8A_UArizona_2024.02.09.xlsx", sheet = "demographics")
Ciitizen_diagnostic = read_excel("./Ciitizen_SCN8A_UArizona_2024.02.09.xlsx",sheet = "diagnostic_procedures")

#only interested in <3 years old here 
Ciitizen_seizures <- Ciitizen_seizures %>% filter(seizure_history_age_days < 1095)
Ciitizen_diagnosis <- Ciitizen_diagnosis %>% filter(clinical_diagnosis_age_days_firstDate<1095)
Ciitizen_hospitalization <- Ciitizen_hospitalization %>% filter(admission_age_days_firstDate<1095)
Ciitizen_medication_weaned <- Ciitizen_medication %>% filter(medication_age_days_lastDate < 1095) 
Ciitizen_diagnostic <- Ciitizen_diagnostic %>% filter(procedure_age_days < 1095)
```

#3. Expanding Dataset to include features of interest
##3.1 Getting Seizure types 
```{r}
seizures <- Ciitizen_seizures 

seizures <- seizures %>% select(c(patient_uuid, seizure_history_type))
seizures_onehot <- as.data.table(seizures)
seizures_onehot$seizure_history_type <- as.factor(seizures_onehot$seizure_history_type)
seizures_onehot <- one_hot(seizures_onehot)

seizures_onehot <- seizures_onehot %>%  group_by(patient_uuid) %>% 
  summarise(across(`seizure_history_type_Absence seizure`:`seizure_history_type_Unprovoked seizure`, max, na.rm=T))
seizures_onehot <- seizures_onehot %>% rename("UUID" = "patient_uuid")
study <- merge(study, seizures_onehot, by = "UUID", all=T)
```

##3.2 Getting Variant
```{r}
scn8a_variant <- Ciitizen_variant %>% filter(gene == "SCN8A")

scn8a_variant <- scn8a_variant %>% group_by(patient_uuid) %>% rename("UUID" = "patient_uuid")

scn8a_variant <- scn8a_variant %>% distinct(UUID, .keep_all = T)

scn8a_variant <- scn8a_variant %>% select(c(UUID, variant_DNA, variant_protein))
study <- merge(study, scn8a_variant, by = "UUID", all = T)
```

##3.3 Getting Hospitalization Events
```{r}
hospitalization <- Ciitizen_hospitalization %>% select(patient_uuid, admission_diagnosis, admission_age_days_firstDate,
                                                       admission_age_days_lastDate)

hospitalization$admission_age_days_firstDate <- as.numeric(hospitalization$admission_age_days_firstDate)
hospitalization$admission_age_days_lastDate <- as.numeric(hospitalization$admission_age_days_lastDate)

length_stay <- apply(hospitalization[3:4],1, diff)
hospitalization <- cbind(hospitalization, length_stay)
hosp_onehot <- as.data.table(hospitalization)
hosp_onehot$admission_diagnosis <- as.factor(hosp_onehot$admission_diagnosis)
hosp_onehot <- one_hot(hosp_onehot)
hosp_final <- hosp_onehot %>% group_by(patient_uuid) %>% 
  summarise(across(`admission_diagnosis_Abnormal movement`:admission_diagnosis_Vomiting, sum, na.rm = T))
hosp_final <- hosp_final %>% rename("UUID"="patient_uuid")
study <- merge(study, hosp_final, by = "UUID", all = T)

hosp_stays <- hosp_onehot %>% group_by(patient_uuid) %>% 
  summarise(across(length_stay, mean, na.rm = T)) %>% rename("UUID"= "patient_uuid")

study <- merge(study, hosp_stays, by = "UUID", all = T)
```

##3.4 Demographics: Sex and Age at diagnosis
```{r}
dems <- Ciitizen_demographics %>% select(patient_uuid, sex, age_at_diagnosis) %>% 
  rename("UUID" = "patient_uuid")

#recode male to 1, female to 0
dems <- dems %>% mutate(sex = ifelse( sex == "male", 1,0))
dems$age_at_diagnosis[ dems$age_at_diagnosis== "undefined"] <- 100
dems$age_at_diagnosis <- as.numeric(dems$age_at_diagnosis)
dems <- dems %>% mutate(age_at_diagnosis_m = age_at_diagnosis*12)

study <- merge(study, dems, by = "UUID", all = T)
study <- study %>% mutate(onset_diagnosis_gap = ifelse(age_at_diagnosis_m<1200, (age_at_diagnosis_m - age_onset_m), "undefined")) %>% select(-age_at_diagnosis)
```

##3.5 Getting Clinical Diagnoses
```{r}
diagnosis <- Ciitizen_diagnosis %>% select(patient_uuid, clinical_diagnosis) %>% 
  rename("UUID" = "patient_uuid")

diagnosis <- as.data.table(diagnosis) 
diagnosis$clinical_diagnosis <- as.factor(diagnosis$clinical_diagnosis)
diagnosis <- one_hot(diagnosis)
diagnosis <- diagnosis %>% group_by(UUID) %>% 
  summarise(across(`clinical_diagnosis_Abdominal pain`:`clinical_diagnosis_West syndrome`, sum, na.rm=T))

study <- merge(study, diagnosis, by = "UUID", all =T)
# write.csv(study, "Supplementary_Table01- Study Data with onset groups.csv")
```

##3.6 Diagnostic Procedure Results
```{r}
test_results <- Ciitizen_diagnostic %>% select(patient_uuid, procedure_findings) %>% 
  rename("UUID" = "patient_uuid")

test_results <- as.data.table(test_results)
test_results$procedure_findings <- as.factor(test_results$procedure_findings)
test_results_onehot <- one_hot(test_results)

test_results_final <- test_results_onehot %>% group_by(UUID) %>% 
  summarise(across(`procedure_findings_Abnormal restricted diffusion`:`procedure_findings_Videofluoroscopy swallow normal`, sum, na.rm=T))

study <- merge(study, test_results_final, by = "UUID", all = T)
```

##3.7 Medications
```{r}
medications <- Ciitizen_medication %>% filter(medication %in% c("Adrenocorticotropin (ACTH 1-18),I-125 (TYR)", 
"Clonazepam", "Levetiracetam", "Phenytoin", "Oxcarbazepine", "Carbamazepine", 
"Phenobarbital", "Lamotrigine", "Briveracetam", "Cannabidiol", "Clobazam", "Epidiolex", 
"Eslicarbazepine", "Ethosuximide", "Felbamate", "Fosphenytoin", "Gabapentin", "Prednisolone",
"Lacosamide", "Primidone", "Pyridoxine", "Rufinamide", "Topiramate", "Valproate", "Vigabatrin", "Zonisamide", "Stiripentol", "Tiagabine", "Acetazolamide", "Clonidine", "Perampanel")) %>% 
  select(-c(3:6, 9:11))

# Function to find stable periods and count medications
find_stable_periods <- function(data) {
  # Sort by first date and last date
  data <- data[order(data$medication_age_days_firstDate,
                     data$medication_age_days_lastDate),]
  
  max_meds <- 0 
  stable_periods <- NULL
  for (i in seq_len(nrow(data))) {
    start_date <- data$medication_age_days_firstDate[i]
    end_date <- data$medication_age_days_lastDate[i]
    
    overlaps <- subset(data,
                       medication_age_days_firstDate <= start_date &
                         medication_age_days_lastDate >= end_date)
    
    # Check if the period is stable
    if ((end_date - start_date >=365) & (nrow(overlaps) > max_meds)) {
      max_meds <- nrow(overlaps)
      stable_periods <- overlaps
    }
  }
  
  if (is.null(stable_periods)) {
    stable_periods <- data[FALSE,]
  }
  
  result <- data.frame(
    patient_uuid = unique(data$patient_uuid),
    age_days_start = ifelse(is.null(stable_periods), NA, min(stable_periods$medication_age_days_firstDate)),
    age_days_end = ifelse(is.null(stable_periods), NA, max(stable_periods$medication_age_days_lastDate)),
    num_stable_meds = ifelse(is.null(stable_periods), NA, nrow(stable_periods))
  )
  return(result)
}

stable_periods <- medications %>%
 group_by(patient_uuid) %>%
 do(find_stable_periods(.))
stable_periods <- stable_periods %>% rename("UUID" = "patient_uuid")

study <- merge(study, subset(stable_periods, select = c(1, 4)), by = "UUID", all=T)
study <- study %>% select(UUID, Onset_group, num_stable_meds, everything())
write.csv(study, "Supplementary_Table01-Population Data.csv")
```

##3.8 EEG Grouping- Abnormal EEGs within the first 3 years of life
```{r}
# Import classifier
classifier <- read_excel(path_classifier)
classifier <- subset(classifier, select = c(1:2, 5, 8))

Ciitizen_eegs = read_excel("./Ciitizen_SCN8A_UArizona_2024.02.09.xlsx", sheet = "diagnostic_procedures")
Ciitizen_eegs <- Ciitizen_eegs[grepl("EEG", Ciitizen_eegs$procedure),]
Ciitizen_eegs <- subset(Ciitizen_eegs, select = -c(2:5, 8:9))

# Filter for range 0-3 years old
Ciitizen_eegs <- Ciitizen_eegs %>% filter(procedure_age_days < 1095)

# One-hot encode abnormal EEG status
Ciitizen_eegs$abnormal_eeg <- with(Ciitizen_eegs, ave(!(procedure_findings %in% classifier$eeg_normal), patient_uuid, FUN = function(x) as.integer(any(x))))
Ciitizen_eegs <- Ciitizen_eegs %>% rename("UUID" = "patient_uuid")
eeg_results <- unique(subset(Ciitizen_eegs, select = c(1, 4)))
study <- merge(study, eeg_results, by = "UUID", all = T) %>% 
  select(UUID, Onset_group, num_stable_meds, abnormal_eeg, everything())
```


