---
title: "Analysis"
author: "Kiran Smelser"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```

```{r}
library(dplyr)
library(tidyverse)
library(data.table)
library(readxl)
library(mltools)
library(ggstatsplot)
```

```{r}
path_data="./data/Supplementary_Table - Study Data by Groups.csv"
path_classifier="./data/ciitizen_health_classifier.xlsx"
```

```{r}
data <- read_csv(path_data)
```


#1 Correlations Between Groups and Seizure Types
##1.1 Initial Seizure Type
```{r}
type_data <- data
new_col_names <- gsub("seizure_history_type_", "", colnames(type_data))
colnames(type_data) <- new_col_names

data_long <- type_data %>%
  gather(key = "initial_seizure_type", value = "value1", focal:infantile) %>%
  gather(key = "seizure_type", value = "value2", `Absence seizure`:`Unprovoked seizure`) %>%
  filter(value1 == 1, value2 == 1) %>%
  group_by(seizure_type) %>%
  mutate(n = n()) %>%
  filter(n >= 15)

# Plot
p_init <- ggbarstats(data_long, initial_seizure_type, seizure_type) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

##1.2 Number of Seizure Types
```{r}
data_long <- type_data %>%
  gather(key = "seizure_type", value = "value2", `Absence seizure`:`Unprovoked seizure`) %>%
  filter(value2 == 1) %>%
  group_by(seizure_type) %>%
  mutate(n = n()) %>%
  filter(n >= 5)

# Plot
p_unique <- ggbarstats(data_long, unique_types, seizure_type) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

##1.3 Abnormal EEG
```{r}
data_long <- data_long %>%
  filter(n >= 7)

# Plot
p_abnormal <- ggbarstats(data_long, abnormal_eeg, seizure_type) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

##1.4 Age of Onset
```{r}
data_long <- data_long %>%
  filter(n >= 10)

# Plot
p_onset <- ggbarstats(data_long, Onset_group, seizure_type) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

##1.5 Save Plots
```{r}
plot <- list(p_init, p_unique, p_abnormal, p_onset)
pdf("./figures/type_plots.pdf", width = 12, height = 8)
plot
dev.off()
```

