---
title: "Descriptive Figures"
author: "Kiran Smelser"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```

```{r}
library(dplyr)
library(tidyverse)
library(data.table)
library(readxl)
library(writexl)
library(ggplot2)
library(ggsci)
library(gridExtra)
library(grid)
library(ggpubr)
library(colorspace)
library(png)
```

```{r}
path_data="./data/Ciitizen_SCN8A_UArizona_2024.02.09.xlsx"
path_classifier="./data/ciitizen_health_classifier.xlsx"
```

```{r}
# Create directory to save plots
dir.create("./figures/descriptive")
```


#1. Seizure Types
```{r}
# Clean and import seizure data
seizure_types <- read_excel(path_data, sheet = "seizure_history")
seizure_types <- subset(seizure_types, select = -c(3:7))

# Import and format seizure type classifier
classifier <- read_excel(path_classifier)
types_classifier <- classifier[grepl("seizure_", names(classifier))]
names(types_classifier) <- sub('^seizure_', '', names(types_classifier))

# Function to add seizure types
find_column_name <- function(value, df) {
  for (col_name in names(df)) {
    if (value %in% df[[col_name]]) {
      return(col_name)
    }
  }
  return(NA)
}

# Classify seizure types
seizure_types$type <- sapply(seizure_types$seizure_history_type, find_column_name, df=types_classifier)
seizure_types <- na.omit(seizure_types)
seizure_types <- subset(seizure_types, select = -c(seizure_history_type))

# Group into other
#seizure_types$type <- replace(seizure_types$type, seizure_types$type %in% c("absence", "clonic", "myoclonic"), "other")

# Remove clonic
seizure_types <- seizure_types[!seizure_types$type == "clonic", ]

# Convert age in days to years
seizure_types$age_years <- seizure_types$seizure_history_age_days / 365

# Convert from wide to long format for ggplot2
long <- seizure_types %>%
  gather(key = "age_type", value = "age_years", age_years)

# Calculate the number of unique patients at ages 1,2,...
patients_by_type <- long %>%
  group_by(type, age_years = floor(age_years)) %>%
  summarise(n = n_distinct(patient_uuid)) %>%
  ungroup()

# Calculate the total number of patients at ages 1,2,...
patients_total <- long %>%
  group_by(age_years = floor(age_years)) %>%
  summarise(total = n_distinct(patient_uuid)) %>%
  ungroup()

# Join the data frames
tmp <- left_join(patients_by_type, patients_total, by = "age_years")

# Divide by the total number of patients at each age
normalized_df <- tmp %>%
  mutate(prop = n / total) %>%
  ungroup()

# Create a smooth line plot
p1_alt <- ggplot(normalized_df, aes(x = age_years, y = prop)) +
  geom_bar(data = patients_total, aes(x = age_years, y = total/max(total)), stat = "identity", fill = "lightgrey", show.legend = FALSE) +
  geom_smooth(method = loess, formula = y~x, se = FALSE, lty = 1,
              method.args = list(span = 1), aes(color = type)) +
  labs(x = "Age (years)", y = "Proportion", color = "Seizure Type") +
  coord_cartesian(xlim = c(0, 10), ylim = c(0, 1)) +
  scale_x_continuous(breaks=0:10) +
  scale_y_continuous(sec.axis = sec_axis(~.*max(patients_total$total), name = "Total Patients")) +
  theme_classic() + 
  scale_color_simpsons()

# Define the order
type_levels <- c("tonic-clonic", "focal", "tonic", "myoclonic", "absence", "spasms")

# Convert 'type' to a factor and specify the order of levels
normalized_df$type <- factor(normalized_df$type, levels = type_levels)

# Plot
p1 <- ggplot(normalized_df, aes(x=age_years, y=prop)) +
  geom_area(stat="smooth", position="identity", method="loess", aes(fill=type)) +
  geom_line(stat = "smooth", method = "loess", formula = y~x, se = FALSE, lty = 1,
            aes(color = type), show.legend = FALSE) +
  #geom_line(data = patients_total, aes(x = age_years, y = total/max(total)), color = "black") +
  #geom_point(data = patients_total, aes(x = age_years, y = total/max(total)), color = "black") +
  #geom_bar(data = patients_total, aes(x = age_years, y = total/max(total)), stat = "identity", fill = NA, color = "black") +
  labs(x="Age (Years)", y="Proportion", fill = "Seizure Type") +
  coord_cartesian(xlim = c(0, 10), ylim = c(0, 1)) +
  scale_x_continuous(breaks=0:10) +
  #scale_y_continuous(sec.axis = sec_axis(~.*max(patients_total$total), name = "Total Patients")) +
  theme_classic() + 
  theme(legend.justification = c(0.05, 1), legend.position = c(0.05, 1)) +
  scale_fill_simpsons() +
  scale_color_simpsons()

ggsave("./figures/descriptive/types.pdf", plot = p1, width = 10, height = 7)
```


#2. Hospitalizations

##2.1 Bar plot
```{r}
# Clean and import hospitalization data
hospitalizations <- read_excel(path_data, sheet = "hospital_admission")
hospitalizations <- subset(hospitalizations, select = c(1:2))

# Import hospitalization classifier
hospitalization_classifier <- read_excel("./data/Grouping Hospitalizations.xlsx")

# Classify hospitalizations
hospitalizations <- left_join(hospitalizations, hospitalization_classifier, by = c("admission_diagnosis"="Hospitalization Events"))
hospitalizations <- hospitalizations[hospitalizations$`Admission Type` %in% c("Emergency", "Incidental"), ]

# Calculate frequency for admission types and subgroups
hospitalizations_freq <- hospitalizations %>%
  group_by(`Admission Type`, Subgroup, admission_diagnosis) %>%
  summarise(n = n()) %>%
  ungroup()
hospitalizations_freq <- na.omit(hospitalizations_freq)

# Create a separate data frame for 'seizure'
seizure_freq <- hospitalizations_freq[hospitalizations_freq$Subgroup == "Seizure", ]
hospitalizations_freq <- hospitalizations_freq[hospitalizations_freq$Subgroup != "Seizure", ]

# Add a new column for facetting
hospitalizations_freq$Facet <- "Other"
seizure_freq$Facet <- "Seizure"

# Combine the data frames
combined_freq <- rbind(hospitalizations_freq, seizure_freq)

# Modify seizure_freq to group all Seizure types that aren't 'Status epilepticus' into 'Non-status epilepticus'
seizure_freq$admission_diagnosis <- ifelse(seizure_freq$admission_diagnosis == "Status epilepticus", "Status epilepticus", "Seizure")

# Create the first plot for 'Other'
p1 <- ggplot(hospitalizations_freq, aes(x=`Admission Type`, y=n, fill=Subgroup)) +
  geom_bar(stat="identity") +
  labs(x="Admission Type", y="# of Reports", fill = "Subgroup") +
  theme_classic() +
  scale_fill_manual(values = c("#FED439FF", "#709AE1FF", "#8A9197FF", "#D2AF81FF", "#FD7446FF", "#D5E4A2FF", "#C80813FF", "#46732EFF", "#FD8CC1FF", "#71D0F5FF")) +
  ggtitle("Other")

# Combine pneumonias and respiratory failures
hospitalizations$admission_diagnosis[hospitalizations$admission_diagnosis=="Aspiration pneumonia"] <- "Pneumonia"
hospitalizations$admission_diagnosis[hospitalizations$admission_diagnosis=="Acute respiratory failure"] <- "Respiratory failure"

# Define the specific hospitalizations to mark
specific_hospitalizations <- c("Respiratory failure", "Pneumonia")

# Calculate sum within each subgroup
specific_hospitalizations_freq <- hospitalizations %>%
  group_by(Subgroup) %>%
  mutate(n = n()) %>%
  ungroup()

# Calculate frequency for specific hospitalizations
specific_hospitalizations_freq <- specific_hospitalizations_freq %>%
  filter(`Admission Type` == "Emergency", admission_diagnosis %in% specific_hospitalizations) %>%
  group_by(`Admission Type`, Subgroup, n, admission_diagnosis) %>%
  summarise(n_specific = n()) %>%
  ungroup()

# Calculate cumulative sum within each subgroup
specific_hospitalizations_freq <- specific_hospitalizations_freq %>%
  arrange(`Admission Type`, Subgroup, admission_diagnosis) %>%
  group_by(`Admission Type`, Subgroup) %>%
  mutate(cumulative_n = cumsum(n_specific)) %>%
  ungroup()

# Create labels
specific_hospitalizations_freq <- specific_hospitalizations_freq %>%
  mutate(label = paste(admission_diagnosis, n_specific, sep = ": "))

# Add text to the bars in the plot
p1 <- p1 + geom_text(data = specific_hospitalizations_freq, aes(label = label, y = cumulative_n), color = "white", size = 2.5)

# Add a lines
p1 <- p1 + geom_segment(data = specific_hospitalizations_freq, aes(x = 0, xend = 1.5, y = cumulative_n - 3, yend = cumulative_n - 3), color = "white")

# Create the second plot for 'Seizure'
p2 <- ggplot(seizure_freq, aes(x=`Admission Type`, y=n, fill=admission_diagnosis)) +
  geom_bar(stat="identity") +
  labs(x="Admission Type", y="# of Reports", fill = "Type") +
  theme_classic() +
  scale_fill_manual(values = c("#370335ff", "#075149ff")) +
  ggtitle("Seizure")

ggsave("./figures/descriptive/hospitalizations_bar.pdf", plot = grid.arrange(p1, p2, ncol=2), width = 10, height = 7)
```

##2.2 Smooth line plot
```{r}
# Clean and import hospitalization data
hospitalizations <- read_excel(path_data, sheet = "hospital_admission")
hospitalizations <- subset(hospitalizations, select = c(1:2, 10))

# Classify hospitalizations
hospitalizations <- left_join(hospitalizations, hospitalization_classifier, by = c("admission_diagnosis"="Hospitalization Events"))
#hospitalizations <- hospitalizations[hospitalizations$`Admission Type` %in% c("Emergency", "Unplanned"), ]

# Split Seizure into Status and Non-status
hospitalizations$Subgroup <- ifelse(hospitalizations$Subgroup == "Seizure" & hospitalizations$admission_diagnosis == "Status epilepticus", "Status epilepticus", ifelse(hospitalizations$Subgroup == "Seizure", "Non-status epilepticus", hospitalizations$Subgroup))

# Convert age in days to years
hospitalizations$admission_age_days_firstDate <- hospitalizations$admission_age_days_firstDate / 365

# Convert from wide to long format for ggplot2
long <- hospitalizations %>%
  gather(key = "age_type", value = "age_years", admission_age_days_firstDate)

# Calculate the number of unique patients at ages 1,2,...
patients_by_subgroup <- long %>%
  group_by(Subgroup, age_years = floor(age_years)) %>%
  summarise(n = n_distinct(patient_uuid)) %>%
  ungroup()

# Calculate the total number of patients at ages 1,2,...
patients_total <- long %>%
  group_by(age_years = floor(age_years)) %>%
  summarise(total = n_distinct(patient_uuid)) %>%
  ungroup()

# Join the data frames
tmp <- left_join(patients_by_subgroup, patients_total, by = "age_years")

# Divide by the total number of patients at each age
normalized_df <- tmp %>%
  mutate(prop = n / total) %>%
  ungroup()
normalized_df <- na.omit(normalized_df)

# Create a smooth line plot
p3 <- ggplot(normalized_df, aes(x = age_years, y = prop)) +
  #geom_bar(data = patients_total, aes(x = age_years, y = total/max(total)), stat = "identity", fill = "lightgrey", show.legend = FALSE) +
  geom_smooth(method = loess, formula = y~x, se = FALSE, lty = 1,
              method.args = list(span = 1), aes(color = Subgroup)) +
  labs(x = "Age (years)", y = "Proportion", color = "Admission Type") +
  coord_cartesian(xlim = c(0, 10), ylim = c(0, 1)) +
  scale_x_continuous(breaks=0:10) +
  #scale_y_continuous(sec.axis = sec_axis(~.*max(patients_total$total), name = "Total Patients")) +
  theme_classic() + 
  theme(legend.justification = c(1, 1), legend.position = c(1, 1)) +
  scale_color_simpsons()

# Filter hospitalizations
normalized_df <- normalized_df[normalized_df$Subgroup %in% c("Status epilepticus", "Non-status epilepticus", "GI", "Infection", "Pulmonary"), ]

# Define the order
type_levels <- c("Non-status epilepticus", "Pulmonary", "Status epilepticus", "Infection", "GI")

# Convert 'Subgroup' to a factor and specify the order of levels
normalized_df$Subgroup <- factor(normalized_df$Subgroup, levels = type_levels)

# Plot
p3_alt <- ggplot(normalized_df, aes(x=age_years, y=prop)) +
  geom_area(stat="smooth", position="identity", method="loess", aes(fill=Subgroup)) +
  geom_line(stat = "smooth", method = "loess", formula = y~x, se = FALSE, lty = 1,
            aes(color = Subgroup), show.legend = FALSE) +
  #geom_line(data = patients_total, aes(x = age_years, y = total/max(total)), color = "black") +
  #geom_point(data = patients_total, aes(x = age_years, y = total/max(total)), color = "black") +
  #geom_bar(data = patients_total, aes(x = age_years, y = total/max(total)), stat = "identity", fill = NA, color = "black") +
  labs(x="Age (Years)", y="Proportion", fill = "Admission Type") +
  coord_cartesian(xlim = c(0, 10), ylim = c(0, .75)) +
  scale_x_continuous(breaks=0:10) +
  #scale_y_continuous(sec.axis = sec_axis(~.*max(patients_total$total), name = "Total Patients")) +
  theme_classic() + 
  scale_fill_simpsons() +
  scale_color_simpsons()

ggsave("./figures/descriptive/hospitalizations_line.pdf", plot = p3, width = 10, height = 7)
```


#3. Diagnoses
```{r}
# Clean and import diagnosis data
diagnoses <- read_excel(path_data, sheet = "clinical_diagnosis_features")
diagnoses <- subset(diagnoses, select = c(1:2, 9))

# Import diagnosis classifier
diagnosis_classifier <- read_excel("./data/Grouping diagnoses.xlsx")
diagnosis_classifier <- subset(diagnosis_classifier, select = -c(5))

# Classify diagnoses
diagnoses <- left_join(diagnoses, diagnosis_classifier, by = c("diagnosis"="Clinical Diagnoses"))

# Count by patient rather than report
diagnoses <- unique(na.omit(subset(diagnoses, select = c(1:2, 6))))

# Filter diagnoses
diagnoses <- diagnoses %>%
  filter(!System %in% c("Endocrine", "Excretory", "Integumentary"))

# Calculate overall percentage for each system
sys_pcts <- diagnoses %>%
  group_by(System) %>%
  summarise(sys_pct = n()/nrow(diagnoses) * 100, sys_n = n())

# Calculate individual diagnosis percentages within each system
diagnosis_pcts <- diagnoses %>%
  group_by(System, diagnosis) %>%
  summarise(diagnosis_n = n())

diagnosis_pcts <- left_join(diagnosis_pcts, subset(sys_pcts, select = -c(2)), by = "System")

diagnosis_pcts <- diagnosis_pcts %>%
  mutate(diagnosis_pct = (diagnosis_n / sys_n) * 100) %>%
  ungroup()
diagnosis_pcts <- subset(diagnosis_pcts, select = -c(3:4))

# Create a list to store dataframes for each system
sys_dfs <- list()

colors <- c("#FD7446FF", "#C80813FF", "#FD8CC1FF", lighten("#46732EFF", 0.25), "#8A9197FF", "#FED439FF", "#71D0F5FF", "#709AE1FF", "#D5E4A2FF", "#D2AF81FF", "#370335FF")

unique_systems <- c("Behavioral", "Musculoskeletal", "Gastrointestil", "Immunological", "Neurological", "Sensory", "Respiratory", "Cardiovascular")

pdf("./figures/descriptive/diagnoses.pdf", width = 12, height = 14)

img <- readPNG("./figures/anatomy.png")

pushViewport(viewport(layout = grid.layout(4, 3, widths = unit(c(.325,.3,.25), "npc"), heights = unit(c(.175,.175,.175,.135), "npc"))))

for (i in 1:length(unique_systems)) {
  system <- unique_systems[i]
  
  # Get the system percentage
  system_pct <- filter(sys_pcts, System == system)$sys_pct
  system_pct <- round(system_pct, 2)
  system_pct <- paste0(system_pct, "%")
  
  # Get the diagnosis percentages for this system
  diagnosis_pct <- filter(diagnosis_pcts, System == system)
  diagnosis_pct <- subset(diagnosis_pct, select = -c(1))
  colnames(diagnosis_pct) = c("Diagnosis", "Percentage")
  
  # Sort the diagnosis percentages in descending order and select the top 7
  diagnosis_pct <- diagnosis_pct[order(-diagnosis_pct$Percentage), ]
  if(nrow(diagnosis_pct) > 7) {
    diagnosis_pct <- diagnosis_pct[1:7, ]
  }
  
  diagnosis_pct$Percentage <- round(diagnosis_pct$Percentage, 2)
  diagnosis_pct$Percentage <- paste0(diagnosis_pct$Percentage, "%")
  
  df <- data.frame(Diagnosis = system, Percentage = system_pct)
  df <- rbind(df, diagnosis_pct)
  colnames(df) <- as.character(unlist(df[1,]))
  df <- df[-1,]
  
  sys_dfs[[system]] <- df

  # Create a table for each dataframe
  table <- ggtexttable(sys_dfs[[system]], rows = NULL, theme = ttheme(
             colnames.style = colnames_style(color = "white", fill = colors[i]),
             tbody.style = tbody_style(color = "black", fill = c(lighten(colors[i], .5)))
           ))

  # Determine the position of the table
  row <- ifelse(i %% 4 == 0, 4, i %% 4)
  col <- ceiling(i / 4)
  if (col == 2) {
    col <- col + 1
  }
  
  print(table, vp = viewport(layout.pos.row = row, layout.pos.col = col))
}

grid.raster(img, width = unit(1, "npc"), height = unit(1.5, "npc"), 
            vp = viewport(layout.pos.row = 2:3, layout.pos.col = 2))
dev.off()
```


#4. Adverse Effects

##4.1 Medication Bar Plot
```{r}
# Clean and import adverse effect data
effects <- read_excel(path_data, sheet = "adverse_effects")
effects <- subset(effects, select = c(1:2, 5, 10:11))
order <- c("Oxcarbazepine", "Lamotrigine", "Valproate", "Phenytoin", "Lacosamide", "Phenobarbital",  "Clobazam", "Levetiracetam", "Topiramate", "Epidiolex")

# Calculate the number of unique patients with a given effect, medication pairing
patients_by_pair <- effects %>%
  group_by(medication_procedure, adverse_effect) %>%
  summarise(n = n_distinct(patient_uuid)) %>%
  ungroup()

# Filter for the top 10 most common medications
top_medications <- patients_by_pair %>%
  group_by(medication_procedure) %>%
  summarise(total_reports = sum(n)) %>%
  top_n(10, total_reports)

# Filter for the top 10 most common adverse effects
top_effects <- patients_by_pair %>%
  group_by(adverse_effect) %>%
  summarise(total_reports = sum(n)) %>%
  top_n(10, total_reports)

# Filter patients_by_pair for reports of top medications and effects
filtered_patients_by_pair <- patients_by_pair %>%
  semi_join(top_medications, by = "medication_procedure")
filtered_patients_by_pair <- filtered_patients_by_pair %>%
  semi_join(top_effects, by = "adverse_effect")

p4 <- ggplot(filtered_patients_by_pair, aes(x=factor(medication_procedure, level=order), y=n, fill=adverse_effect)) +
  geom_bar(stat="identity") +
  labs(x="Medication", y="# of Patients", fill = "Adverse Effect") +
  scale_fill_manual(values = c("#ffde76", "#bacfec", "#8A9197FF", "#f1b682", "#e37c1d", "#abb47d", "#a30234", "#67771a", "#e4b8b4", "#5698a3")) +
  theme_classic() 

ggsave("./figures/descriptive/effects_by_med.pdf", plot = p4, width = 12, height = 8)
```

##4.2 Severity Bar Plot
```{r}
# Clean and import adverse effect data
effects <- read_excel(path_data, sheet = "adverse_effects")
effects <- subset(effects, select = c(1:2, 5, 10:11))

# Import adverse effect classifier
effect_classifier <- read_excel("./data/effects_severity.xlsx")

# Classify adverse effects
effects <- left_join(effects, effect_classifier, by = "adverse_effect")

# Remove `medication not effective`
effects <- subset(effects, effects$adverse_effect != "Medication not effective")

# Calculate the number of unique patients with a given effect, severity pairing
patients_by_severity <- effects %>%
  group_by(severity_score, adverse_effect) %>%
  summarise(n = n_distinct(patient_uuid)) %>%
  ungroup()

# Filter for the top 10 most common adverse effects
filtered_patients_by_severity <- patients_by_severity %>%
  top_n(10, n)

p5 <- ggplot(na.omit(filtered_patients_by_severity), aes(x=severity_score, y=n, fill=adverse_effect)) +
  geom_bar(stat="identity") +
  labs(x="Severity", y="# of Patients", fill = "Adverse Effect") +
  scale_fill_manual(values = c("#ffde76", "#bacfec", "#8A9197FF", "#f1b682", "#e37c1d", "#abb47d", "#a30234", "#67771a", "#e4b8b4", "#5698a3")) +
  theme_classic() 

ggsave("./figures/descriptive/effects_by_severity.pdf", plot = p5, width = 10, height = 7)
```


# Medications
```{r}
# Clean and import hospitalization data
meds <- read_excel(path_data, sheet = "medication")
meds <- subset(meds, select = c(1:2, 7:8))

# Filter medications
meds_to_use <- paste(c("Adrenocorticotropin (ACTH 1-18),I-125 (TYR)", "Clonazepam", "Levetiracetam", "Phenytoin", "Oxcarbazepine", "Carbamazepine", "Phenobarbital", "Lamotrigine", "Briveracetam", "Cannabidiol", "Clobazam", "Epidiolex", "Eslicarbazepine", "Ethosuximide", "Felbamate","Gabapentin", "Prednisolone", "Lacosamide", "Primidone", "Rufinamide", "Topiramate", "Valproate", "Vigabatrin", "Zonisamide", "Stiripentol", "Tiagabine", "Perampanel"), collapse = "|")
meds <- meds %>%
  mutate(medication = ifelse(grepl("ACTH", medication), "ACTH", medication),
         medication = recode(medication, Epidiolex="Epidiolex/CBD", Cannabidiol = "Epidiolex/CBD"))
meds <- subset(meds, grepl(meds_to_use, medication))
top <- meds %>%
  count(medication) %>%
  top_n(10)
meds <- meds %>%
  filter(medication %in% top$medication)

# Convert age in days to years
meds$medication_age_days_firstDate <- meds$medication_age_days_firstDate / 365

# Convert from wide to long format for ggplot2
long <- meds %>%
  gather(key = "age_type", value = "age_years", medication_age_days_firstDate)

# Calculate the number of unique patients at ages 1,2,...
patients_by_medication <- long %>%
  group_by(medication, age_years = floor(age_years)) %>%
  summarise(n = n_distinct(patient_uuid)) %>%
  ungroup()

# Calculate the total number of patients at ages 1,2,...
patients_total <- long %>%
  group_by(age_years = floor(age_years)) %>%
  summarise(total = n_distinct(patient_uuid)) %>%
  ungroup()

# Join the data frames
tmp <- left_join(patients_by_medication, patients_total, by = "age_years")

# Divide by the total number of patients at each age
normalized_df <- tmp %>%
  mutate(prop = n / total) %>%
  ungroup()
normalized_df <- na.omit(normalized_df)

order <- c("Oxcarbazepine", "Lamotrigine", "Valproate","Phenytoin", "Lacosamide", "Phenobarbital",  "Clonazepam", "Clobazam", "Levetiracetam", "Topiramate")
line_types <- c("Oxcarbazepine" = "solid", "Lamotrigine" = "solid", "Lacosamide" = "solid", "Valproate" = "solid", "Phenytoin" = "solid", "Phenobarbital" = "dotted", "Clonazepam" = "dotted", "Clobazam" = "dotted", "Levetiracetam" = "dotdash", "Topiramate" = "dashed")

# Create a smooth line plot
p6 <- ggplot(normalized_df, aes(x = age_years, y = prop)) +
  geom_smooth(method = loess, formula = y~x, se = FALSE, aes(color = factor(medication, level = order), linetype = factor(medication, level = order)), method.args = list(span = 1)) +
  labs(x = "Age (years)", y = "Proportion", color = "Medication", linetype = "Medication") +
  coord_cartesian(xlim = c(0, 10), ylim = c(0, 1)) +
  scale_x_continuous(breaks=0:10) +
  theme_classic() + 
  theme(legend.justification = c(1, 1), legend.position = c(1, 1)) +
  scale_color_manual(values = c("#ffde76", "#bacfec", "#8A9197FF", "#f1b682", "#e37c1d", "#abb47d", "#a30234", "#67771a", "#e4b8b4", "#5698a3")) +
  scale_linetype_manual(values = line_types)

ggsave("./figures/descriptive/meds.pdf", plot = p6, width = 10, height = 7)
```

